#http
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:2.19
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - "3627:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - export:/usr/src/paperless/export
      - consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_OCR_LANGUAGES: deu
      PAPERLESS_URL: https://paperless.by.vincent.mahn.ke
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
        {"openid_connect": {"APPS": [{"provider_id": "keycloak","name": "${OAUTH_NAME}","client_id": "${OAUTH_CLIENT_ID}","secret": "${OAUTH_CLIENT_SECRET}","settings": { "server_url": "${OAUTH_URL}/.well-known/openid-configuration"}}]}}
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_CONSUMPTION_DIR: ../consume/rsync
      
  webdav-sync:
    image: rclone/rclone:1.71
    restart: unless-stopped
    volumes:
      - consume:/data/consume
      - rclonedata:/config/rclone
    entrypoint:
      - /bin/sh
      - -c
      - |
        cat > /config/rclone/rclone.conf <<EOF
        [remote]
        type = webdav
        url = ${NEXTCLOUD_HOST}/remote.php/dav/files/${NEXTCLOUD_USERNAME}
        vendor = nextcloud
        user = ${NEXTCLOUD_USERNAME}
        pass = $(rclone obscure "${NEXTCLOUD_PASSWORD}")
        EOF

        while true; do
          rclone -vv bisync remote:Paperless /data/consume --delete-during --transfers 4 --checkers 8 --low-level-retries 10 --timeout 1m --create-empty-src-dirs --resilient --recover --max-lock 2m --conflict-resolve newer
          sleep 10
        done

volumes:
  data:
  media:
  export:
  consume:
  redisdata:
  rclonedata:
