#http
version: "3.4"
services:
  broker:
    image: docker.io/library/redis:8
    restart: unless-stopped
    volumes:
      - redisdata:/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - "3627:8000"
    healthcheck:
      test: ["CMD", "curl", "-fs", "-S", "--max-time", "2", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - export:/usr/src/paperless/export
      - consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_OCR_LANGUAGES: deu
      PAPERLESS_URL: https://paperless.by.vincent.mahn.ke
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
        {"openid_connect": {"APPS": [{"provider_id": "keycloak","name": "${OAUTH_NAME}","client_id": "${OAUTH_CLIENT_ID}","secret": "${OAUTH_CLIENT_SECRET}","settings": { "server_url": "${OAUTH_URL}/.well-known/openid-configuration"}}]}}
      PAPERLESS_REDIS: redis://broker:6379

volumes:
  data:
  media:
  export:
  consume:
  redisdata:
